# Generated by Django 4.0 on 2022-01-05 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('marks', models.FloatField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department_Professor_Student.department')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Professor_name', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('department_id', models.ManyToManyField(to='Department_Professor_Student.Department')),
            ],
        ),
    ]
