# Generated by Django 4.0 on 2022-01-06 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Department_Professor_Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='department_id',
            field=models.ManyToManyField(related_name='department_pro', to='Department_Professor_Student.Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_stud', to='Department_Professor_Student.department'),
        ),
    ]
